version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: curriculum-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      # 로케일이 꼭 ko_KR이어야 하면 아래 주석 해제(이미지에 로케일 설치 필요)
      # POSTGRES_INITDB_ARGS: "--locale=C.UTF-8"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - curriculum-net

  # Neo4j - 지식 그래프 저장
  neo4j:
    image: neo4j:5.15-community
    container_name: curriculum-neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/neo4j123
      NEO4J_dbms_memory_heap_initial__size: 256m
      NEO4J_dbms_memory_heap_max__size: 512m
      NEO4J_dbms_memory_pagecache_size: 256m
      NEO4J_dbms_jvm_additional: "-Dfile.encoding=UTF-8"
    ports:
      - "7474:7474"  # HTTP 브라우저
      - "7687:7687"  # Bolt 연결
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "neo4j123", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - curriculum-net

  # Redis - 캐싱
  redis:
    image: redis:7-alpine
    container_name: curriculum-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - curriculum-net

networks:
  curriculum-net:

volumes:
  pg_data:
  pgadmin_data:
  neo4j_data:
  neo4j_logs:
  redis_data:
